# Generated by Django 3.2.5 on 2021-07-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'name', 'verbose_name_plural': 'names'},
        ),
    ]
